    LIST P=16F883
    INCLUDE P16F883.INC
    ERRORLEVEL -302
    
    __CONFIG _CONFIG1, _DEBUG_OFF & _LVP_OFF & _FCMEN_OFF & _IESO_OFF & _BOR_ON & _CPD_OFF & _CP_OFF & _MCLRE_OFF & _PWRTE_ON & _WDT_OFF & _XT_OSC
    __CONFIG _CONFIG2, _WRT_OFF
    
    CBLOCK    0X20
    PDel0, PDel1, DECENAS, UNIDADES, CUENTA     ; Creamos la variable CUENTA    ***CAMBIO***
    ENDC
    


    ORG    00
    GOTO    CONFIGURA

;-------------------------------------------------------------
; Code generated by PDEL  ver 1.0  on 14/10/2010 at 03:01:16 p.m.
; Description: Waits 10000 cycles
;-------------------------------------------------------------
RET_10MS  movlw     .8        ; 1 set number of repetitions (B)
        movwf     PDel0     ; 1 |
PLoop1  movlw     .249      ; 1 set number of repetitions (A)
        movwf     PDel1     ; 1 |
PLoop2  clrwdt              ; 1 clear watchdog
        clrwdt              ; 1 cycle delay
        decfsz    PDel1, 1  ; 1 + (1) is the time over? (A)
        goto      PLoop2    ; 2 no, loop
        decfsz    PDel0,  1 ; 1 + (1) is the time over? (B)
        goto      PLoop1    ; 2 no, loop
PDelL1  goto PDelL2         ; 2 cycles delay
PDelL2  clrwdt              ; 1 cycle delay
        return              ; 2+2 Done
;-------------------------------------------------------------
        
TABLA    ADDWF    PCL,F
    RETLW    B'00111111'
    RETLW    B'00000110'
    RETLW    B'01011011'
    RETLW    B'01001111'
    RETLW    B'01100110'
    RETLW    B'01101101'
    RETLW    B'01111100'
    RETLW    B'00000111'
    RETLW    B'01111111'
    RETLW    B'01101111'
    
MOSTRAR    MOVF    UNIDADES,W    ;cargo el valor de las unidades
    CALL    TABLA
    BSF    PORTC,5    ;activo el display unidad
    BCF    PORTC,4    ;desactivo el display decena
    MOVWF    PORTB
    CALL    RET_10MS
    MOVF    DECENAS,W    ;cargo el valor de las decenas
    CALL    TABLA
    BCF    PORTC,5    ;desactivo el display unidad
    BSF    PORTC,4    ;activo el display decena
    MOVWF    PORTB
    CALL    RET_10MS
    RETURN
    
VER    CALL    MOSTRAR
    CALL    MOSTRAR
    CALL    MOSTRAR
    CALL    MOSTRAR
    CALL    MOSTRAR
    CALL    MOSTRAR
    CALL    MOSTRAR
    CALL    MOSTRAR    ;LOGRO UN RETARDO DE 160ms
    RETURN
    
CONFIGURA    NOP
    BANKSEL    ANSEL    ;paso al banco 3
    CLRF    ANSEL    ;Configura el porta como digital
    CLRF    ANSELH    ;Configura el portb como digital
    BANKSEL    TRISB    ;paso al banco 1
    CLRF    ANSEL
    MOVLW    0X00
    MOVWF    TRISA
    MOVLW    0X00
    MOVWF    TRISB
    MOVLW    0X00
    MOVWF    TRISC
    BANKSEL    PORTB    ;paso al banco 0
    CLRF    PORTB
    CLRF    DECENAS
    CLRF    UNIDADES
    CLRF    CUENTA                                                              ; ***CAMBIO***
    


;******este bloque se agrega para comprobar si llego a determinado numero******

CICLO1      MOVLW       .20         ;este es el valor tope 0 hasta 99    !!!VALOR TOPE!!!       ; ***CAMBIO***
            XORWF       CUENTA,W    ;compruebo si llego al tope                 ; ***CAMBIO***
            GOTO        CICLO       ; no llego al tope                          ; ***CAMBIO***
            CLRF        CUENTA      ;llego al tope, reinicio la cuenta global   ; ***CAMBIO***
            CLRF        UNIDADES                                                ; ***CAMBIO*** 
            CLRF        DECENAS                                                 ; ***CAMBIO***
            CALL        VER                                                     ; ***CAMBIO***
;******************************************************************************

CICLO       CALL        VER    ;Esta rutina me sirve como un
            ;retardo de 20ms aprox
            INCF        CUENTA,F        ;cuenta global    ; ***CAMBIO***
            INCF        UNIDADES,F
            MOVLW       .10
            XORWF       UNIDADES,W
            BTFSC       STATUS,Z
            GOTO        INC_DECENAS
            CALL        VER
            GOTO        CICLO1          ; ***CAMBIO***
    
INC_DECENAS    CLRF    UNIDADES
            INCF        DECENAS,F
            MOVLW       .10
            XORWF       DECENAS,W
            BTFSC       STATUS,Z
            CLRF        DECENAS
            CLRF        CUENTA          ; ***CAMBIO***
            CALL        VER
            GOTO        CICLO1          ; ***CAMBIO***
                
            END
